name: Build and Upload Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ubuntu environment
        run: |
          sudo apt update
          sudo apt install -y \
            sed \
            make \
            binutils \
            build-essential \
            diffutils \
            gcc \
            g++ \
            bash \
            patch \
            gzip \
            bzip2 \
            perl \
            tar \
            cpio \
            unzip \
            rsync \
            file \
            bc  \
            findutils \
            wget \
            git

      - name: Create buildroot directory
        run: mkdir /buildroot

      - name: Clone buildroot repository
        run: git clone --depth 1 --branch 2024.02.2 https://github.com/buildroot/buildroot.git /buildroot

      - name: Copy buildroot config
        run: cp ./buildroot-src/.config /buildroot/.config

      - name: buildroot make all
        working-directory: /buildroot
        run: make all

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: buildroot-output
          path: /buildroot/output
